In [1]:

from neural_networks.utils.data_structures import AttrDict

layer_1 = AttrDict(
    {
        "name": "fully_connected",
        "activation": 'sigmoid',# YOUR CODE HERE,
        "weight_init": "xavier_uniform",
        "n_out": 20   # YOUR CODE HERE,
    }
)

layer_out = AttrDict(
    {
        "name": "fully_connected",
        "activation": 'sigmoid',# YOUR CODE HERE,
        "weight_init": "xavier_uniform",
        "n_out": None
        # n_out is not defined for last layer. This will be set by the dataset.
    }
)

"""
Step 2: Collect layer argument dictionaries into a list.

- This defines the order of layers in the network.
"""

layer_args = [layer_1, layer_out]

"""
Step 3: Define model, data, and logger arguments

- The list of layer_args is passed to the model initializer.
"""

optimizer_args = AttrDict(
    {
        "name": "SGD",
        "lr": 0.1,# YOUR CODE HERE,
        "lr_scheduler": 'constant', # YOUR CODE HERE
        "lr_decay": 0.005,# YOUR CODE HERE,
        "stage_length": 1, # YOUR CODE HERE,
        "staircase": False,# YOUR CODE HERE,
        "clip_norm": 1, # YOUR CODE HERE,
        "momentum": 0.04 # YOUR CODE HERE,
    }
)

model_args = AttrDict(
    {
        "loss": 'cross_entropy',# YOUR CODE HERE,
        "layer_args": layer_args,
        "optimizer_args": optimizer_args,
        "seed": 189,# YOUR CODE HERE,
        'name':'Higgs two layer' ###########
    }
)

data_args = AttrDict(
    {
        "name": "higgs", # YOUR CODE HERE, name of dataset, e.g. "iris"
        "batch_size": 10 # YOUR CODE HERE,
    }
)

log_args = AttrDict(
    {"save": True, "plot": True, "save_dir": "kaggle/",}
)

"""
Step 4: Set random seed

Warning! Random seed must be set before importing other modules.
"""

import numpy as np

np.random.seed(model_args.seed)

"""
Step 5: Define model name for saving
"""

model_name = 'Higgs'+'_layer_size='+str(layer_1['n_out'])+'_lr='+str(optimizer_args['lr'])

"""
Step 6: Initialize logger, model, and dataset

- model_name, model_args, and data_args are passed to the logger for saving
- The logger is passed to the model.
"""

from neural_networks.models import initialize_model
from neural_networks.datasets import initialize_dataset
from neural_networks.logs import Logger


logger = Logger(
    model_name=model_name,
    model_args=model_args,
    data_args=data_args,
    save=log_args.save,
    plot=log_args.plot,
    save_dir=log_args.save_dir,
)


model = initialize_model(
    name=model_args.name,
    loss=model_args.loss,
    layer_args=model_args.layer_args,
    optimizer_args=model_args.optimizer_args,
    logger=logger,
)


dataset = initialize_dataset(
    name=data_args.name,
    batch_size=data_args.batch_size,
)


"""
Step 7: Train model!
"""

epochs = 50

print(
    "Training {} neural network on {} with {} for {} epochs...".format(
        model_args.name, data_args.name, optimizer_args.name, epochs
    )
)

print("Optimizer:")
print(optimizer_args)

model.train(dataset, epochs=epochs)
model.test(dataset) # For Higgs, call test_kaggle() to generate the Kaggle file.

  0%|          | 0/50000 [00:00<?, ?it/s]

Training Higgs two layer neural network on higgs with SGD for 50 epochs...
Optimizer:
{'name': 'SGD', 'lr': 0.1, 'lr_scheduler': 'constant', 'lr_decay': 0.005, 'stage_length': 1, 'staircase': False, 'clip_norm': 1, 'momentum': 0.04}


  0%|          | 0/50000 [00:00<?, ?it/s]

Example target: [1. 0.]
Example prediction: [1.0, 1.0]
Epoch 0 Training Loss: 0.0003 Training Accuracy: 0.5426 Val Loss: 0.0 Val Accuracy: 0.5433


  0%|          | 1/50000 [00:00<2:14:29,  6.20it/s]

Example target: [1. 0.]
Example prediction: [1.0, 1.0]
Epoch 1 Training Loss: 0.0 Training Accuracy: 0.5461 Val Loss: 0.0 Val Accuracy: 0.5451


  0%|          | 1/50000 [00:00<1:46:02,  7.86it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 2 Training Loss: 0.0 Training Accuracy: 0.5472 Val Loss: 0.0 Val Accuracy: 0.5453


  0%|          | 1/50000 [00:00<2:13:23,  6.25it/s]

Example target: [1. 0.]
Example prediction: [1.0, 1.0]
Epoch 3 Training Loss: 0.0 Training Accuracy: 0.5481 Val Loss: 0.0 Val Accuracy: 0.5461


  0%|          | 0/50000 [00:00<?, ?it/s]

Example target: [1. 0.]
Example prediction: [1.0, 1.0]
Epoch 4 Training Loss: 0.0 Training Accuracy: 0.5486 Val Loss: 0.0 Val Accuracy: 0.5468


  0%|          | 1/50000 [00:00<2:28:38,  5.61it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 5 Training Loss: 0.0 Training Accuracy: 0.5491 Val Loss: 0.0 Val Accuracy: 0.5473


  0%|          | 1/50000 [00:00<2:09:19,  6.44it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 6 Training Loss: 0.0 Training Accuracy: 0.5496 Val Loss: 0.0 Val Accuracy: 0.5478


  0%|          | 1/50000 [00:00<2:25:37,  5.72it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 7 Training Loss: 0.0 Training Accuracy: 0.5499 Val Loss: 0.0 Val Accuracy: 0.5481


  0%|          | 0/50000 [00:00<?, ?it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 8 Training Loss: 0.0 Training Accuracy: 0.5501 Val Loss: 0.0 Val Accuracy: 0.5483


  0%|          | 1/50000 [00:00<2:13:50,  6.23it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 9 Training Loss: 0.0 Training Accuracy: 0.5503 Val Loss: 0.0 Val Accuracy: 0.5486


  0%|          | 1/50000 [00:00<2:30:01,  5.55it/s]

Example target: [1. 0.]
Example prediction: [1.0, 1.0]
Epoch 10 Training Loss: 0.0 Training Accuracy: 0.5505 Val Loss: 0.0 Val Accuracy: 0.5488


  0%|          | 1/50000 [00:00<1:33:44,  8.89it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 11 Training Loss: 0.0 Training Accuracy: 0.5507 Val Loss: 0.0 Val Accuracy: 0.5491


  0%|          | 0/50000 [00:00<?, ?it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 12 Training Loss: 0.0 Training Accuracy: 0.5509 Val Loss: 0.0 Val Accuracy: 0.5493


  0%|          | 1/50000 [00:00<2:19:35,  5.97it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 13 Training Loss: 0.0 Training Accuracy: 0.551 Val Loss: 0.0 Val Accuracy: 0.5495


  0%|          | 1/50000 [00:00<2:27:11,  5.66it/s]

Example target: [1. 0.]
Example prediction: [1.0, 1.0]
Epoch 14 Training Loss: 0.0 Training Accuracy: 0.5511 Val Loss: 0.0 Val Accuracy: 0.5498


  0%|          | 0/50000 [00:00<?, ?it/s]

Example target: [0. 1.]
Example prediction: [1.0, 1.0]
Epoch 15 Training Loss: 0.0 Training Accuracy: 0.5513 Val Loss: 0.0 Val Accuracy: 0.5498


 26%|██▌       | 12758/50000 [00:10<00:31, 1186.20it/s]

KeyboardInterrupt: 

In [8]:
import numpy as np
a = np.matrix('-1 1; 3 1')
b = np.matrix('-1 2; 3 4')
b[a!=1]=1
a

matrix([[-1,  1],
        [ 3,  1]])

In [3]:
np.tanh(a)

matrix([[-0.76159416,  0.76159416],
        [ 0.99505475,  0.76159416]])

 26%|██▌       | 12758/50000 [00:30<00:31, 1186.20it/s]

In [9]:
np.tanh(3)

0.9950547536867305

In [38]:
1/(1+np.exp(-2))

0.8807970779778823

In [28]:
np.exp(-a)

matrix([[2.71828183, 0.13533528],
        [0.04978707, 0.01831564]])

In [31]:
np.exp(-a)+1

matrix([[3.71828183, 1.13533528],
        [1.04978707, 1.01831564]])

In [32]:
1/(np.exp(-a)+1)

matrix([[0.26894142, 0.88079708],
        [0.95257413, 0.98201379]])